object Dependencies {
    const val androidx_core = "androidx.core:core-ktx:1.12.0"
    const val androidx_lifecycle_runtime = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle_ktx}"
    const val androidx_lifecycle_vm = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle_ktx}"
    const val androidx_activity_compose = "androidx.activity:activity-compose:1.8.2"
    const val composeBOM = "androidx.compose:compose-bom:${Versions.compose_bom}"
    const val compose_ui = "androidx.compose.ui:ui"
    const val compose_ui_graphic = "androidx.compose.ui:ui-graphics"
    const val compose_tooling_preview ="androidx.compose.ui:ui-tooling-preview"
    const val compose_material3 = "androidx.compose.material3:material3"
    const val hilt = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val hilt_compiler = "com.google.dagger:hilt-android-compiler:${Versions.hilt}"
    const val hilt_nav_compose = "androidx.hilt:hilt-navigation-compose:${Versions.hilt_compose_nav}"
    const val compose_viewmodel = "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.compose_view_model}"
    const val compose_navigation = "androidx.navigation:navigation-compose:${Versions.compose_nav}"
    const val kotlin_coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
    const val retorfit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val gson_converter = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val okHtttp = "com.squareup.okhttp3:okhttp:${Versions.okhtttp}"
    const val javaxInject = "javax.inject:javax.inject:1"
}